### ISSUE TITLE
Assignment-4 : Reverse String

### ISSUE THREAD

**Issue by 55bit23** [vtcbca/basic-programming-43bit23#3]
Can you reverse a string entered by the user?

**Comment by 43bit23** [comment]
Yes, take input with input() and reverse it using slicing:

```
user_input = input("Enter a string: ")
reversed_string = user_input[::-1]
```

**Comment by 55bit23** [comment]
What happens if you reverse an empty string?

**Comment by 43bit23** [comment]
Reversing an empty string returns an empty string.

**Comment by 55bit23** [comment]
Can a string contain numbers and special characters?

**Comment by 43bit23** [comment]
Yes, strings can include any combination of characters, like "12345" or "Hello!@".

**Comment by 55bit23** [comment]
How do you reverse a string without using slicing?

**Comment by 43bit23** [comment]
Use a loop to build the reversed string:

```
reversed_string = ""
for char in string:
    reversed_string = char + reversed_string
```

**Comment by 55bit23** [comment]
Is the original string modified after reversing?

**Comment by 43bit23** [comment]
No, strings are immutable, so reversing creates a new string.
